# Generated by Django 2.1.2 on 2018-10-18 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=140)),
                ('lodge_address', models.TextField()),
                ('arrive_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('members_booked', models.ManyToManyField(related_name='lodge_members_booked', to=settings.AUTH_USER_MODEL)),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('depart_loc', models.CharField(max_length=140)),
                ('arrive_loc', models.CharField(max_length=140)),
                ('depart_time', models.DateField()),
                ('arrive_time', models.DateField()),
                ('members_booked', models.ManyToManyField(related_name='logistic_members_booked', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('home_town', models.CharField(blank=True, max_length=30)),
                ('current_loc', models.CharField(blank=True, max_length=30)),
                ('join_date', models.DateField(blank=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zantta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zantta_name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('members', models.ManyToManyField(related_name='zantta_members', to='zanttana.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='msgs',
            name='Zantta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zanttana.Zantta'),
        ),
        migrations.AddField(
            model_name='msgs',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logistics',
            name='zantta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_zanta', to='zanttana.Zantta'),
        ),
    ]
