# Generated by Django 2.1.2 on 2018-10-18 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanttana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='members_booked',
            field=models.ManyToManyField(blank=True, related_name='lodge_members_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='members_booked',
            field=models.ManyToManyField(blank=True, related_name='logistic_members_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zantta',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='zantta_members', to='zanttana.Profile'),
        ),
    ]
